# Generated by Django 4.0.4 on 2022-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='mike', max_length=500),
            preserve_default=False,
        ),
    ]
