# Generated by Django 4.0.4 on 2022-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
