# Generated by Django 4.0.4 on 2022-05-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_published_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
