# Generated by Django 4.0.4 on 2022-05-27 08:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=['ad', 'dd'], size=None),
            preserve_default=False,
        ),
    ]
