# Generated by Django 4.0.4 on 2022-05-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_published_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
