# Generated by Django 4.0.4 on 2022-05-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_unique id, external_id pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unique id, external_id pair',
        ),
    ]
