# Generated by Django 4.0.4 on 2022-05-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_remove_book_unique id, external_id pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='external_id',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
